export const ItemTypes = {
    ELEMENT:"ELEMENT"
}

export const constants = {
    LOAD_DYNAMIC_PARAMS:"LOAD_DYNAMIC_PARAMS",
    CREATE_DYNAMIC_PARAM:"CREATE_DYNAMIC_PARAM",
    DELETE_DYNAMIC_PARAM:"DELETE_DYNAMIC_PARAM",
    EDIT_DYNAMIC_PARAM:"EDIT_DYNAMIC_PARAM",
}


export const START = "_START"
export const SUCCESS = "_SUCCESS"
export const FAIL = "_FAIL"